site_name: PingOne DaVinci Partner Connectors
repo_name: pingone-davinci/connector-docs
repo_url: https://github.com/pingone-davinci/connector-docs
site_url: https://pingone-davinci.github.io/connector-docs/
copyright: © Copyright 2022 Ping Identity
extra_css:
  - mkdocs/overrides/stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - instant

  palette:
    - media: "(prefers-color-scheme: light)"
      accent: blue
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      accent: blue
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.snippets
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

plugins:
  - search:
        separator: '[\s\-\.]+'
  - redirects:
     redirect_maps:
       deployment/deployPdgPap.md: "deployment/deployPazPap.md"

nav:
  - Partner Connectors:
      - Beyond Identity: "beyondidentity/README.md"
      - Circle Access: "circleaccess/README.md"
 
